import React from "react";
import { Navbar } from "../components/Navbar";
import { Footer } from "../components/Footer";
import { New } from "../components/New";
import '../styles/AllNews.css';

export const AllNews = () => {
    return (
        <>
            <Navbar />
            <section className="allNewsSection">
                <h2>Novedades</h2>
                <article className="boxNews">
                    <New img={"https://plus.unsplash.com/premium_photo-1712128931969-5075b31d9380?q=80&w=1469&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"} date={new Date()} title={"NUEVOS ANALÍTICOS"} info={"Estimado/as. Llegaron a nuestro instituto una nueva tanda de ANALÍTICOS DEFINITIVOS EN PAPEL MONEDA   Los listados están publicados en el Menu - EGRESADOS de Lunes a viernes de 19:00 a 22 hs  Sede IPEM N° 6. “Juan Filloy” B ° Gral. Paz Dirección: Viamonte 1005 - B° Gral..."} eventClick={() => window.location.href = `/news/${1}`} />
                    <New img={"https://images.unsplash.com/photo-1711907392527-4a895b190b61?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"} date={new Date()} title={"CARRERAS CON CUPOS ANOTATE!!!"} info={"No te pierdas la oportunidad de estudiar con nosotros! Aún tenemos cupos en las Tecnicaturas Superiores de:   Administración:  Inscripción Presencial: de Lunes a viernes de 19:00 a 22 hs  Sede IPEM N° 6. “Juan Filloy” B ° Gral. Paz Dirección: Viamonte 1005 - B° Gr..."} />
                    <New img={"https://images.unsplash.com/photo-1711968558539-1bcc5b6222db?q=80&w=1333&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"} date={new Date()} title={"ATENCIÓN - TODAS LAS CARRERAS- MATRICULACIÓN 2024"} info={"Info para ENFERMERÍA y las demas carreras. Si no completaste tu matriculación definitiva en diciembre del 2023, acercate desde el lunes 19/02 a: RÍO NEGRO 77 B° ALBERDI Del 19 al 23 de Febrero del 2024 De 9 a 17 hs    Documentación a presentar ..."} />
                    <New img={"https://plus.unsplash.com/premium_photo-1712128931969-5075b31d9380?q=80&w=1469&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"} date={new Date()} title={"NUEVOS ANALÍTICOS"} info={"Estimado/as. Llegaron a nuestro instituto una nueva tanda de ANALÍTICOS DEFINITIVOS EN PAPEL MONEDA   Los listados están publicados en el Menu - EGRESADOS de Lunes a viernes de 19:00 a 22 hs  Sede IPEM N° 6. “Juan Filloy” B ° Gral. Paz Dirección: Viamonte 1005 - B° Gral..."} />
                    <New img={"https://images.unsplash.com/photo-1711907392527-4a895b190b61?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"} date={new Date()} title={"CARRERAS CON CUPOS ANOTATE!!!"} info={"No te pierdas la oportunidad de estudiar con nosotros! Aún tenemos cupos en las Tecnicaturas Superiores de:   Administración:  Inscripción Presencial: de Lunes a viernes de 19:00 a 22 hs  Sede IPEM N° 6. “Juan Filloy” B ° Gral. Paz Dirección: Viamonte 1005 - B° Gr..."} />
                    <New img={"https://images.unsplash.com/photo-1711968558539-1bcc5b6222db?q=80&w=1333&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"} date={new Date()} title={"ATENCIÓN - TODAS LAS CARRERAS- MATRICULACIÓN 2024"} info={"Info para ENFERMERÍA y las demas carreras. Si no completaste tu matriculación definitiva en diciembre del 2023, acercate desde el lunes 19/02 a: RÍO NEGRO 77 B° ALBERDI Del 19 al 23 de Febrero del 2024 De 9 a 17 hs    Documentación a presentar ..."} />
                    <New img={"https://plus.unsplash.com/premium_photo-1712128931969-5075b31d9380?q=80&w=1469&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"} date={new Date()} title={"NUEVOS ANALÍTICOS"} info={"Estimado/as. Llegaron a nuestro instituto una nueva tanda de ANALÍTICOS DEFINITIVOS EN PAPEL MONEDA   Los listados están publicados en el Menu - EGRESADOS de Lunes a viernes de 19:00 a 22 hs  Sede IPEM N° 6. “Juan Filloy” B ° Gral. Paz Dirección: Viamonte 1005 - B° Gral..."} />
                    <New img={"https://images.unsplash.com/photo-1711907392527-4a895b190b61?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"} date={new Date()} title={"CARRERAS CON CUPOS ANOTATE!!!"} info={"No te pierdas la oportunidad de estudiar con nosotros! Aún tenemos cupos en las Tecnicaturas Superiores de:   Administración:  Inscripción Presencial: de Lunes a viernes de 19:00 a 22 hs  Sede IPEM N° 6. “Juan Filloy” B ° Gral. Paz Dirección: Viamonte 1005 - B° Gr..."} />
                    <New img={"https://images.unsplash.com/photo-1711968558539-1bcc5b6222db?q=80&w=1333&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"} date={new Date()} title={"ATENCIÓN - TODAS LAS CARRERAS- MATRICULACIÓN 2024"} info={"Info para ENFERMERÍA y las demas carreras. Si no completaste tu matriculación definitiva en diciembre del 2023, acercate desde el lunes 19/02 a: RÍO NEGRO 77 B° ALBERDI Del 19 al 23 de Febrero del 2024 De 9 a 17 hs    Documentación a presentar ..."} />
                    <New img={"https://plus.unsplash.com/premium_photo-1712128931969-5075b31d9380?q=80&w=1469&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"} date={new Date()} title={"NUEVOS ANALÍTICOS"} info={"Estimado/as. Llegaron a nuestro instituto una nueva tanda de ANALÍTICOS DEFINITIVOS EN PAPEL MONEDA   Los listados están publicados en el Menu - EGRESADOS de Lunes a viernes de 19:00 a 22 hs  Sede IPEM N° 6. “Juan Filloy” B ° Gral. Paz Dirección: Viamonte 1005 - B° Gral..."} />
                    <New img={"https://images.unsplash.com/photo-1711907392527-4a895b190b61?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"} date={new Date()} title={"CARRERAS CON CUPOS ANOTATE!!!"} info={"No te pierdas la oportunidad de estudiar con nosotros! Aún tenemos cupos en las Tecnicaturas Superiores de:   Administración:  Inscripción Presencial: de Lunes a viernes de 19:00 a 22 hs  Sede IPEM N° 6. “Juan Filloy” B ° Gral. Paz Dirección: Viamonte 1005 - B° Gr..."} />
                    <New img={"https://images.unsplash.com/photo-1711968558539-1bcc5b6222db?q=80&w=1333&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"} date={new Date()} title={"ATENCIÓN - TODAS LAS CARRERAS- MATRICULACIÓN 2024"} info={"Info para ENFERMERÍA y las demas carreras. Si no completaste tu matriculación definitiva en diciembre del 2023, acercate desde el lunes 19/02 a: RÍO NEGRO 77 B° ALBERDI Del 19 al 23 de Febrero del 2024 De 9 a 17 hs    Documentación a presentar ..."} />
                </article>
            </section>
            <Footer />
        </>
    );
}